deploy:
  image: php:8.2
  stage: testing
  before_script:
    - date
    - php --version
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && php composer-setup.php && php -r "unlink('composer-setup.php');" && mv composer.phar /usr/local/bin/composer
    - composer --version
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - npm install
    - npm run build
    - vendor/bin/phpunit
stages:
  - testing