variables:
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite

test:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
      - node_modules/
  image: jhordybarreradev/ubuntu-laravel:latest
  before_script:
    - date
    - php --version
    - composer --version
    - node --version
    - npm --version
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - chmod -R 755 storage bootstrap/cache
    - touch database/database.sqlite
    - php artisan migrate
    - npm install
    - npm run build
    - vendor/bin/phpunit

deploy_develop:
  image: jhordybarreradev/ubuntu-laravel:latest
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install ssh -y
    - mkdir -p ~/.ssh
    - echo "$CD_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - touch ~/.ssh/config
    - echo "HOST *" > ~/.ssh/config
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - curl ifconfig.me

  script:
    - echo "Deploying develop!"
    - ssh $CD_USER@$CD_DEVELOP_HOST -i secure-files/id_rsa "cd $CD_PATH && composer install && npm install && npm run build && php artisan migrate" 
  after_script:
    - rm -rf ~/.ssh
  only:
    - develop
  when: on_success
  