variables:
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite

test:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
      - node_modules/
  image: jhordybarreradev/ubuntu-laravel:latest
  before_script:
    - date
    - php --version
    - composer --version
    - node --version
    - npm --version
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - chmod -R 755 storage bootstrap/cache
    - touch database/database.sqlite
    - php artisan migrate
    - npm install
    - npm run build
    - vendor/bin/phpunit

deploy_develop:
  variables:
    SECURE_FILES_DOWNLOAD_PATH: 'secure-files'
  script:
    - apt update && apt install curl ssh -y
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - chmod 600 secure-files/$CD_KEY
    - echo "Deploying develop!"
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - echo "HOST *" > ~/.ssh/config
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - curl ifconfig.me
    - ssh $CD_USER@$CD_DEVELOP_HOST -i secure-files/$CD_KEY "cd $CD_PATH && composer install && npm install && npm run build && php artisan migrate" 
  only:
    - develop
  when: on_success
  