deploy:
  image: jhordybarreradev/ubuntu-laravel:latest
  stage: testing
  before_script:
    - date
    - php --version
    - composer --version
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - npm install
    - npm run build
    - vendor/bin/phpunit
stages:
  - testing