variables:
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite
test:
  image: jhordybarreradev/ubuntu-laravel:latest
  stage: testing
  before_script:
    - date
    - php --version
    - composer --version
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - chmod -R 777 storage bootstrap/cache
    - touch database/database.sqlite
    - php artisan migrate
    - npm install
    - npm run build
    - php artisan test
    # - vendor/bin/phpunit
stages:
  - testing