variables:
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite
default:
  cache: &global_cache
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
      - node_modules/
test:
  image: jhordybarreradev/ubuntu-laravel:latest
  before_script:
    - date
    - php --version
    - composer --version
    - node --version
    - npm --version
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - chmod -R 755 storage bootstrap/cache
    - touch database/database.sqlite
    - php artisan migrate
    - npm install
    - npm run build
    - vendor/bin/phpunit

job:
  <<: *global_cache
  script: echo "This job does NOT create double pipelines!"
  