name: Laravel

on:
  push:
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: build-${{ hashFiles('package-lock.json') }}
    - name: Build assets
      run: |
        npm install
        npm run build
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

  laravel-deployment:
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude='.env' --exclude='public' --exclude='vendor' --exclude='node_modules' --exclude='storage' --exclude='bootstrap/cache' --exclude='*.log'
        path: ./
        remote_path: ${{ secrets.REMOTE_PATH }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_port: ${{ secrets.REMOTE_PORT }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.REMOTE_KEY }}

    - name: Check if composer.json changed
      id: composer_changed
      run: echo ::set-output name=CHANGED::$(if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'composer\.json'; then echo true; else echo false; fi)

    - name: Composer Install
      if: steps.composer_changed.outputs.CHANGED == 'true'
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -p ${{ secrets.REMOTE_PORT }} "cd ${{ secrets.REMOTE_PATH }} && composer install"

    - name: Check for changes in CSS and JS files or package.json
      uses: tj-actions/verify-changed-files@v19
      id: check_changes
      with:
        files: |
            resources/js
            resources/css
            package.json

    - name: Run npm install and build
      if: steps.check_changes.outputs.files_changed == 'true'
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -p ${{ secrets.REMOTE_PORT }} "cd ${{ secrets.REMOTE_PATH }} && npm install && npm run build"
